# Generated by Django 5.1.5 on 2025-07-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_userbase_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
