# Generated by Django 5.1.5 on 2025-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_userbase_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('upi', 'UPI')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
